<div class="card-body">
  <table class="table">
    <thead>
    <tr>
      <th>번호</th>
      <th>제목</th>
      <th>작성자</th>
      <th>모델</th>
      <th>상태</th>
      <th>등록일</th>
    </tr>
    </thead>
    <tbody>
    <tr>
      <td>1</td>
      <td>배송문의</td>
      <td>김철수</td>
      <td>아이폰15</td>
      <td>답변대기</td>
      <td>2024-03-20</td>
    </tr>
    <tr>
      <td>2</td>
      <td>환불요청</td>
      <td>이영희</td>
      <td>맥북프로</td>
      <td>답변완료</td>
      <td>2024-03-19</td>
    </tr>
    <tr>
      <td>3</td>
      <td>제품문의</td>
      <td>박지민</td>
      <td>애플워치</td>
      <td>답변중</td>
      <td>2024-03-18</td>
    </tr>
    </tbody>
  </table>
</div>